[phases.setup]
aptPkgs = ["...", "python"]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput",
    "python manage.py compress",
]

[start]
cmd = "gunicorn <your_project>.wsgi --bind 0.0.0.0:8080"
