# nixpacks.toml

[build]
# Specify the providers to use
providers = ["python"]

# Commands to run during the build phase
commands = [
    "python manage.py compress", # Compress static files
    "python manage.py collectstatic --noinput"  # Collect static files
]
